# Generated by Django 3.2.9 on 2021-11-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='short_description',
            field=models.CharField(default='My short', max_length=60),
            preserve_default=False,
        ),
    ]
