# Generated by Django 3.2.9 on 2021-11-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_remove_disease_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
